name: "Example workflow for Robot Framework"

on:
  push:
  workflow_dispatch:

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Execute tests
        run: |
          docker run \
            -v ${{ github.workspace }}/tests:/opt/robotframework/reports:Z \
            -v ${{ github.workspace }}/results:/opt/robotframework/tests:Z \
            ppodgorsek/robot-framework:latest
              
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: results
          path: ${{ github.workspace }}/results

